### ISSUE TITLE
libx264 bad codec?

### ISSUE THREAD

**Issue by vdegenne** [ammen99/wf-recorder#274] opened 2024-08-13 18:48 UTC
I have this command in one of my script:
```bash
wf-recorder -c libx264 -g "$REGION" -f "$OUTPUT" &
```

When I record and send the file on socials (e.g. telegram), some friends say they can't read the video. And on X/Twitter it is even worse, it tells something like "error uploading".
Do you have the same issue with this codec which usually works fine everywhere? Could it be an issue with `wf-recorder` ?

**Comment by vdegenne** [comment] 2024-08-13 19:05
Ok I think I understand the problem, If I run `wf-recorder` in a terminal and use CTRL-c it works but what I'm trying to accomplish here is writing a "toggle" script, if `wf-recorder` runs in the background I kill it or else I execute it.
The killing part must be too brutal (using `pkill -SIGTERM -x "wf-recorder"`), Not sure how I could simulate ctrl-c on a thread, anyone knows?

**Comment by marcusbritanicus** [comment] 2024-08-13 19:09
`SIGINT` is what you are looking for.

**Comment by kernaltrap8** [comment] 2024-08-13 19:10
yes, libx264 is in fact, a bad codec :trollface:

**Comment by soreau** [comment] 2024-08-13 19:10
But it should handle `SIGTERM` and `SIGHUP` as well. See [this line](https://github.com/ammen99/wf-recorder/blob/master/src/main.cpp#L40). However this is a scripting issue, not a wf-recorder issue, so closing.

**Closed by soreau** 2024-08-13 19:10 UTC

**Comment by vdegenne** [comment] 2024-08-13 19:23
I don't understand it still doesn't work, here's my screen:
```bash
#!/bin/bash

# Check if wf-recorder is already running
if pgrep -x "wf-recorder" >/dev/null; then
  # Gracefully stop the currently running recording using SIGINT
  pkill -SIGINT -x "wf-recorder"
else
  OUTPUT="$HOME/Videos/screencast_$(date +%Y-%m-%d_%H-%M-%S).mp4"
  REGION=$(slurp)

  # Check if slurp was canceled or failed (exit status 1)
  if [ $? -ne 0 ]; then
    exit 1
  fi

  wf-recorder --audio=alsa_output.pci-0000_08_00.6.analog-stereo.monitor -c libx264 -g "$REGION" -f "$OUTPUT"
fi
```

What's wrong?

**Comment by vdegenne** [comment] 2024-08-13 19:28
Something I forgot to mention is that I execute the script using a keymap registered in `wayfire.ini`:

```conf
binding_4 = <ctrl> <alt> KEY_L
command_4 = ~/bin/cycle-layout.sh
```

Not sure if that's what cause the issue or not.

**Comment by vdegenne** [comment] 2024-08-13 19:54
@soreau Are you 100% sure it is not a problem with `wf-recorder` sending SIGINT to `wf-recorder` will kill the process and I have a video file which appears to work in some places like YouTube but not x.com, however using ctrl-c on `wf-recorder` will work. Could it be a problem with the way `wf-recorder` handles signals and forward them to `ffmpeg` ?

**Comment by kernaltrap8** [comment] 2024-08-13 20:09
> @soreau Are you 100% sure it is not a problem with `wf-recorder` ? Sending SIGINT to `wf-recorder` will kill the process and I have a video file which appears to work in some places like YouTube but not x.com, however using ctrl-c on `wf-recorder` will work. Could it be a problem with the way `wf-recorder` handles signals and forward them to `ffmpeg` ?

C^c sends the same signal. if you send SIGINT via pkill, the same behavior should occur when using C^c

**Comment by vdegenne** [comment] 2024-08-13 20:33
@kernaltrap8 ok thanks, I think my problem is with the `--audio` (I could swear I had no problem with it in the past), so I'll have to figure out which codec to use with this parameter.

Thanks for your help

**Comment by ammen99** [comment] 2024-08-14 05:20
@vdegenne Codec support can be spotty. Many people report that videos sometimes do not play depending on browser, app, etc. It is not a bug in wf-recorder but just poor support in the ecosystem. See for example #222 #198 #202

**Comment by tannerellen** [comment] 2024-08-15 05:49
I'm running into the same issue with my libx264 videos playing fine on my linux desktop but not on my iPhone or iPad (in the browser). It appears that this is based on the metdata setting "major_brand" which is set to isom by default. I can't figure out a way to pass a new brand through wl-recorder so I use ffmpeg directly on the file after it is created like so... ffmpeg -i in.mp4 -brand mp42 out.mp4

**Comment by vdegenne** [comment] 2024-08-15 10:09
@tannerellen Yes in my case I kept having issues uploading to X. So what I ended up doing was to convert the file produced by `wf-recorder` using this `ffmpeg` command:

```bash
ffmpeg -i "$FILE" -c:v libx264 -crf 20 -preset slow -vf format=yuv420p -c:a aac -movflags 
 +faststart "$OUTPUT"
```
(source: https://stackoverflow.com/questions/59056863/i-cant-upload-this-video-file-mp4-to-twitter)

I wish I didn't have to use this extra step, but I couldn't find any other way.

**Comment by vdegenne** [comment] 2024-08-15 10:22
If I remove `-vf format=yuv420p` in the above command it fails again. @ammen99 Is there any way to pass that argument to `wf-recorder` directly?

**Comment by vdegenne** [comment] 2024-08-15 22:07
@soreau I use `0.4.0` and the default produces a choppy video file I don't know why, that's why I am using `libx264`

**Comment by soreau** [comment] 2024-08-15 23:21
I recommend you try latest from git with default options.

**Comment by vdegenne** [comment] 2024-08-16 09:58
@soreau Awesome! It works like a charm now :smiley:  Thanks for the help every time.

(By the way I am on Fedora here, I don't know who's responsible for updating the packages, but wayfire and associated packages are always at an older version.)
