### ISSUE TITLE
Maximum file size?

### ISSUE THREAD

**Issue by h-2** [ammen99/wf-recorder#95] opened 2020-05-14 18:46 UTC
I recorded a long video-call today that lasted 1:23h. Everything worked fine until about 1:10h at which point wf-recorder started printing lots of these lines:
```
[mp4 @ 0x7f4370000d00] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 386544055 >= 64755793  
[mp4 @ 0x7f4370000d00] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 386544055 >= 64760065 
```

In the resulting file the video is missing after 1:10h. Seeking there with MPV crashes MPV, but VLC plays the file fine and has audio after 1:10h but no video.

No extra args beyond `--audio` were provided. Version is 0.2 on Void Linux.

**Comment by soreau** [comment] 2020-05-14 19:25
Duplicate of #78. Please try latest.

**Closed by soreau** 2020-05-14 19:25 UTC

**Comment by ammen99** [comment] 2020-05-14 20:31
Also worth mentioning, there is a 0.2.1 release which already has a fix for this bug, you might want to report the package to be updated.
