### ISSUE TITLE
Driver does not support some wanted packed headers (wanted 0xd, found 0)

### ISSUE THREAD

**Issue by bool3max** [ammen99/wf-recorder#44] opened 2019-07-24 17:49 UTC
Using latest build built using the AUR package. 

Running `$ wf-recorder -f test.mkv -c h264_vaapi -d /dev/dri/renderD128` results in the following: 

```
selected region 0 0 0 0
[h264_vaapi @ 0x7fb2c4001f80] Driver does not support some wanted packed headers (wanted 0xd, found 0).
[h264_vaapi @ 0x7fb2c4001f80] Driver does not support packed sequence headers, but a global header is requested.
[h264_vaapi @ 0x7fb2c4001f80] No global header will be written: this may result in a stream which is not usable for some purposes (e.g. not muxable to some containers).
Output #0, matroska, to 'test.mkv':
    Stream #0:0: Unknown: none (h264_vaapi)
[matroska @ 0x7fb2c4000c80] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Failed to write file header
```

I'm using an AMD RX 580 on Arch (kernel 5.2.1).

Output of `$ vainfo`: 
```

vainfo: VA-API version: 1.5 (libva 2.5.0)
vainfo: Driver version: Mesa Gallium driver 19.1.3 for Radeon RX 580 Series (POLARIS10, DRM 3.32.0, 5.2.1-arch1-1-ARCH, LLVM 8.0.1)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc
```

I've also tried using the `-t` flag, same result.

**Comment by ammen99** [comment] 2019-07-24 21:26
Have you been able to record with h264 under X11 and the `ffmpeg` command directly? This looks like a missing feature in your driver/ffmpeg build.

**Comment by ammen99** [comment] 2019-07-25 07:47
I would also try changing the file extension to something other than .mkv (maybe .mp4 or similar)

**Comment by bool3max** [comment] 2019-07-25 18:11
Using an `.mp4` extension works, but only if `-t` is passed as well. 

`.mkv` doesn't work regardless of whether `-t` is passed. Weird.

**Comment by soreau** [comment] 2019-07-26 15:47
@bool3max The -t option is needed to convert the rgb data to yuv before passing it to the libva driver radeonsi_drv_video.so because it cannot handle rgb data directly. The .mkv file format should work as long as ffmpeg you're using is built with matroska support. Check the output of `ffmpeg -formats|egrep "matroska|mp4"` to see what it supports.

**Comment by soreau** [comment] 2019-07-26 15:59
Actually what I said is only true when not using the -t option or vaapi. With -t which is required for vaapi on radeonsi_drv_video.so, I can reproduce the issue you describe. mkv gives the messages you describe and with mp4 there is different behavior. Since I am using latest fmmpeg, I get "[h264_vaapi @ 0x7fdb7c001b40] This encoder requires using the avcodec_send_frame() API." every frame.

**Comment by soreau** [comment] 2019-07-27 06:38
It appears that mkv not working is due to [a bug in ffmpeg/libav](https://lists.ffmpeg.org/pipermail/ffmpeg-user/2018-March/039090.html). You'd also need `videoCodecCtx->max_b_frames = 0;` to get this going. Maybe report there that this problem affects you too.

**Comment by soreau** [comment] 2019-07-27 17:10
I also found out mkv works with this mesa patch to report support for packed headers http://ix.io/1PIT

**Comment by bool3max** [comment] 2019-07-27 18:39
I'll try that patch later, thanks!

**Comment by soreau** [comment] 2019-07-28 16:26
After chatting with some driver devs, this apparently is the wrong fix. It's reporting packed headers are implemented when they're not, creating a technically incorrect (though working in most video players) file. Also I've found that apparently the .mp4's created with vaapi are incorrect too but it checks were only in place for mkv so mp4 incorrectly works.

**Comment by ammen99** [comment] 2019-07-28 18:17
@soreau So in the end, is there something we're doing wrong or this just missing features in the driver/ffmpeg ?

**Comment by soreau** [comment] 2019-07-28 18:18
@ammen99 It's just the gallium va state tracker drivers, I'm guessing this works fine with intel vaapi.

**Comment by bool3max** [comment] 2019-07-28 18:19
Yeah, vaapi recording works with my intel igpu.

**Comment by ammen99** [comment] 2019-07-28 18:22
Ok, so closing this issue. Reopen it if there is something we can do (and which isn't a hack such as the max_b_frames)

**Closed by ammen99** 2019-07-28 18:22 UTC
