### ISSUE TITLE
Feature Request: audio from speakers and mic

### ISSUE THREAD

**Issue by ubone** [ammen99/wf-recorder#134] opened 2021-01-07 09:32 UTC
pulseaudio allows to record both (desktop) audio you hear and audio from your microphone

ffmpeg -f pulse -i input-mic -f pulse -i output-speaker -filter_complex amix output.mkv

`pactl list sources` shows the names

**Comment by ammen99** [comment] 2021-01-07 09:34
Is this a duplicate of #131 ?

**Comment by ubone** [comment] 2021-01-07 15:43
yes

**Comment by ammen99** [comment] 2021-01-07 15:58
Then, the same answer applies: check the wiki for instructions how to set this up in pulseaudio.

As a side note: I have no plans for implementing multiple audio sources, and I would consider a PR implementing such functionality only if it adds minimal complexity.

**Closed by ammen99** 2021-01-07 15:58 UTC
